# Generated by Django 4.0.6 on 2022-07-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RfQuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('que', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RfRoomDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('roomId', models.CharField(max_length=20)),
                ('playerId', models.CharField(max_length=20)),
                ('playerName', models.CharField(max_length=18)),
            ],
            options={
                'unique_together': {('roomId', 'playerId')},
                'index_together': {('roomId', 'playerId')},
            },
        ),
    ]
