# Generated by Django 3.1.2 on 2021-09-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RfRoomDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('roomId', models.CharField(max_length=20)),
                ('playerId', models.CharField(max_length=20)),
                ('playerName', models.CharField(max_length=20)),
            ],
        ),
    ]
