# Generated by Django 3.1.2 on 2021-09-09 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf', '0002_rfroomdetail'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rfroomdetail',
            unique_together={('roomId', 'playerId')},
        ),
        migrations.AlterIndexTogether(
            name='rfroomdetail',
            index_together={('roomId', 'playerId')},
        ),
    ]
