# Generated by Django 3.1.2 on 2021-10-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HowWellUKnow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('que', models.CharField(max_length=200)),
                ('optionA', models.CharField(max_length=80)),
                ('optionB', models.CharField(max_length=80)),
                ('optionC', models.CharField(max_length=80)),
                ('optionD', models.CharField(max_length=80)),
                ('ans', models.IntegerField()),
                ('image', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='HowWellUKnowScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('score', models.IntegerField()),
                ('complement', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=600)),
            ],
        ),
    ]
