# Generated by Django 3.1.2 on 2021-09-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewGames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('link', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=300)),
            ],
        ),
    ]
