# Generated by Django 3.2.2 on 2021-09-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='user',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.CharField(max_length=18),
        ),
    ]
