from .models import *

# change all these before run
# n u l l  =  None
# t r u e  =  True
# f a l s e  =  False
# change all img field with image location (location must be in media folder)

QuizQue=[
    {
        "category": "friends",
        "part1": "What is",
        "part2": "'s favorite sport?",
        "optionA": "Cricket",
        "optionB": "Ludo",
        "optionC": "PUBG",
        "optionD": "Subway Surfers",
    },
    {
        "category": "friends",
        "part1": "If",
        "part2": "could be a superhero for a day, who would it be?",
        "optionA": "Ironman",
        "optionB": "Superman",
        "optionC": "Thor",
        "optionD": "Captain America",
    },
    {
        "category": "friends",
        "part1": "What is the best gift",
        "part2": "has received?",
        "optionA": "Mobile",
        "optionB": "Crush Mobile No.",
        "optionC": "Bike",
        "optionD": "",
    },
    {
        "category": "friends",
        "part1": "How many kids will",
        "part2": "have?",
        "optionA": "2",
        "optionB": "3",
        "optionC": "4",
        "optionD": "11",
    },
    {
        "category": "friends",
        "part1": "Which messages do",
        "part2": "prefer?",
        "optionA": "Text Message",
        "optionB": "Call",
        "optionC": "Voice mail",
        "optionD": "Video Chat",
    },
    {
        "category": "friends",
        "part1": "Which pet would",
        "part2": "choose?",
        "optionA": "Dog",
        "optionB": "Cat",
        "optionC": "Squirrel",
        "optionD": "Nothing",
    },
    {
        "category": "friends",
        "part1": "Which device",
        "part2": "mostly use?",
        "optionA": "Mobile",
        "optionB": "Laptop",
        "optionC": "Tablets",
        "optionD": "Nothing",
    },
    {
        "category": "friends",
        "part1": "Copied 2 Which device",
        "part2": "mostly use?",
        "optionA": "Mobile",
        "optionB": "Laptop",
        "optionC": "Tablets",
        "optionD": "Nothing",
    },
    {
        "category": "friends",
        "part1": "Copied 2 Which device",
        "part2": "mostly use?",
        "optionA": "Mobile",
        "optionB": "Laptop",
        "optionC": "Tablets",
        "optionD": "Nothing",
    },
    {
        "category": "friends",
        "part1": "Copied 3 Which device",
        "part2": "mostly use?",
        "optionA": "Mobile",
        "optionB": "Laptop",
        "optionC": "Tablets",
        "optionD": "Nothing",
    },
    {
        "category": "friends",
        "part1": "Copied 4 Which device",
        "part2": "mostly use?",
        "optionA": "Mobile",
        "optionB": "Laptop",
        "optionC": "Tablets",
        "optionD": "Nothing",
    },
    {
        "category": "friends",
        "part1": "Copied 5 Which device",
        "part2": "mostly use?",
        "optionA": "Mobile",
        "optionB": "Laptop",
        "optionC": "Tablets",
        "optionD": "Nothing",
    },
    {
        "category": "friends",
        "part1": "Copied 6 Which device",
        "part2": "mostly use?",
        "optionA": "Mobile",
        "optionB": "Laptop",
        "optionC": "Tablets",
        "optionD": "Nothing",
    },
    {
        "category": "friends",
        "part1": "Copied 7 Which device",
        "part2": "mostly use?",
        "optionA": "Mobile",
        "optionB": "Laptop",
        "optionC": "Tablets",
        "optionD": "Nothing",
    },
    {
        "category": "friends",
        "part1": "Copied 8 Which device",
        "part2": "mostly use?",
        "optionA": "Mobile",
        "optionB": "Laptop",
        "optionC": "Tablets",
        "optionD": "Nothing",
    },



    {
        "category": "couples",
        "part1": "couples What is",
        "part2": "'s favorite sport?",
        "optionA": "Cricket",
        "optionB": "Ludo",
        "optionC": "PUBG",
        "optionD": "Subway Surfers",
    },
    {
        "category": "couples",
        "part1": "couples If",
        "part2": "could be a superhero for a day, who would it be?",
        "optionA": "Ironman",
        "optionB": "Superman",
        "optionC": "Thor",
        "optionD": "Captain America",
    },
    {
        "category": "couples",
        "part1": "couples What is the best gift",
        "part2": "has received?",
        "optionA": "Mobile",
        "optionB": "Crush Mobile No.",
        "optionC": "Bike",
        "optionD": "",
    },
    {
        "category": "couples",
        "part1": "couples How many kids will",
        "part2": "have?",
        "optionA": "2",
        "optionB": "3",
        "optionC": "4",
        "optionD": "11",
    },
    {
        "category": "couples",
        "part1": "couples Which messages do",
        "part2": "prefer?",
        "optionA": "Text Message",
        "optionB": "Call",
        "optionC": "Voice mail",
        "optionD": "Video Chat",
    },
    {
        "category": "couples",
        "part1": "couples Which pet would",
        "part2": "choose?",
        "optionA": "Dog",
        "optionB": "Cat",
        "optionC": "Squirrel",
        "optionD": "Nothing",
    },
    {
        "category": "couples",
        "part1": "couples Which device",
        "part2": "mostly use?",
        "optionA": "Mobile",
        "optionB": "Laptop",
        "optionC": "Tablets",
        "optionD": "Nothing",
    },
    {
        "category": "couples",
        "part1": "couples Copied 2 Which device",
        "part2": "mostly use?",
        "optionA": "Mobile",
        "optionB": "Laptop",
        "optionC": "Tablets",
        "optionD": "Nothing",
    },
    {
        "category": "couples",
        "part1": "couples Copied 2 Which device",
        "part2": "mostly use?",
        "optionA": "Mobile",
        "optionB": "Laptop",
        "optionC": "Tablets",
        "optionD": "Nothing",
    },
    {
        "category": "couples",
        "part1": "couples Copied 3 Which device",
        "part2": "mostly use?",
        "optionA": "Mobile",
        "optionB": "Laptop",
        "optionC": "Tablets",
        "optionD": "Nothing",
    },
    {
        "category": "couples",
        "part1": "couples Copied 4 Which device",
        "part2": "mostly use?",
        "optionA": "Mobile",
        "optionB": "Laptop",
        "optionC": "Tablets",
        "optionD": "Nothing",
    },
    {
        "category": "couples",
        "part1": "couples Copied 5 Which device",
        "part2": "mostly use?",
        "optionA": "Mobile",
        "optionB": "Laptop",
        "optionC": "Tablets",
        "optionD": "Nothing",
    },
    {
        "category": "couples",
        "part1": "couples Copied 6 Which device",
        "part2": "mostly use?",
        "optionA": "Mobile",
        "optionB": "Laptop",
        "optionC": "Tablets",
        "optionD": "Nothing",
    },
    {
        "category": "couples",
        "part1": "couples Copied 7 Which device",
        "part2": "mostly use?",
        "optionA": "Mobile",
        "optionB": "Laptop",
        "optionC": "Tablets",
        "optionD": "Nothing",
    },
    {
        "category": "couples",
        "part1": "couples Copied 8 Which device",
        "part2": "mostly use?",
        "optionA": "Mobile",
        "optionB": "Laptop",
        "optionC": "Tablets",
        "optionD": "Nothing",
    },



    {
        "category": "bff",
        "part1": "bff What is",
        "part2": "'s favorite sport?",
        "optionA": "Cricket",
        "optionB": "Ludo",
        "optionC": "PUBG",
        "optionD": "Subway Surfers",
    },
    {
        "category": "bff",
        "part1": "bff If",
        "part2": "could be a superhero for a day, who would it be?",
        "optionA": "Ironman",
        "optionB": "Superman",
        "optionC": "Thor",
        "optionD": "Captain America",
    },
    {
        "category": "bff",
        "part1": "bff What is the best gift",
        "part2": "has received?",
        "optionA": "Mobile",
        "optionB": "Crush Mobile No.",
        "optionC": "Bike",
        "optionD": "",
    },
    {
        "category": "bff",
        "part1": "bff How many kids will",
        "part2": "have?",
        "optionA": "2",
        "optionB": "3",
        "optionC": "4",
        "optionD": "11",
    },
    {
        "category": "bff",
        "part1": "bff Which messages do",
        "part2": "prefer?",
        "optionA": "Text Message",
        "optionB": "Call",
        "optionC": "Voice mail",
        "optionD": "Video Chat",
    },
    {
        "category": "bff",
        "part1": "bff Which pet would",
        "part2": "choose?",
        "optionA": "Dog",
        "optionB": "Cat",
        "optionC": "Squirrel",
        "optionD": "Nothing",
    },
    {
        "category": "bff",
        "part1": "bff Which device",
        "part2": "mostly use?",
        "optionA": "Mobile",
        "optionB": "Laptop",
        "optionC": "Tablets",
        "optionD": "Nothing",
    },
    {
        "category": "bff",
        "part1": "bff Copied 2 Which device",
        "part2": "mostly use?",
        "optionA": "Mobile",
        "optionB": "Laptop",
        "optionC": "Tablets",
        "optionD": "Nothing",
    },
    {
        "category": "bff",
        "part1": "bff Copied 2 Which device",
        "part2": "mostly use?",
        "optionA": "Mobile",
        "optionB": "Laptop",
        "optionC": "Tablets",
        "optionD": "Nothing",
    },
    {
        "category": "bff",
        "part1": "bff Copied 3 Which device",
        "part2": "mostly use?",
        "optionA": "Mobile",
        "optionB": "Laptop",
        "optionC": "Tablets",
        "optionD": "Nothing",
    },
    {
        "category": "bff",
        "part1": "bff Copied 4 Which device",
        "part2": "mostly use?",
        "optionA": "Mobile",
        "optionB": "Laptop",
        "optionC": "Tablets",
        "optionD": "Nothing",
    },
    {
        "category": "bff",
        "part1": "bff Copied 5 Which device",
        "part2": "mostly use?",
        "optionA": "Mobile",
        "optionB": "Laptop",
        "optionC": "Tablets",
        "optionD": "Nothing",
    },
    {
        "category": "bff",
        "part1": "bff Copied 6 Which device",
        "part2": "mostly use?",
        "optionA": "Mobile",
        "optionB": "Laptop",
        "optionC": "Tablets",
        "optionD": "Nothing",
    },
    {
        "category": "bff",
        "part1": "bff Copied 7 Which device",
        "part2": "mostly use?",
        "optionA": "Mobile",
        "optionB": "Laptop",
        "optionC": "Tablets",
        "optionD": "Nothing",
    },
    {
        "category": "bff",
        "part1": "bff Copied 8 Which device",
        "part2": "mostly use?",
        "optionA": "Mobile",
        "optionB": "Laptop",
        "optionC": "Tablets",
        "optionD": "Nothing",
    },
]

def add_quizque():
    try:
        print("try quiz que")
        if len(QuizQuestionBank.objects.all()):
            print("quiz que already have que")
            return 0

        for data in QuizQue:
            print("quiz que added")
            QuizQuestionBank.objects.create(
                category = data["category"],
                part1 = data["part1"],
                part2 = data["part2"],
                optionA = data["optionA"],
                optionB = data["optionB"],
                optionC = data["optionC"],
                optionD = data["optionD"],
            )
        print("try quiz que complete")
    except:
        print("except in quiz que")
        pass



def add_data():
    print("Quiz")
    add_quizque()
