# Generated by Django 3.1.2 on 2021-09-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouLookLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('que1', models.CharField(max_length=200)),
                ('option1A', models.CharField(max_length=50)),
                ('option1B', models.CharField(max_length=50)),
                ('option1C', models.CharField(blank=True, max_length=50, null=True)),
                ('option1D', models.CharField(blank=True, max_length=50, null=True)),
                ('image1', models.CharField(blank=True, max_length=800, null=True)),
                ('que2', models.CharField(max_length=200)),
                ('option2A', models.CharField(max_length=50)),
                ('option2B', models.CharField(max_length=50)),
                ('option2C', models.CharField(blank=True, max_length=50, null=True)),
                ('option2D', models.CharField(blank=True, max_length=50, null=True)),
                ('image2', models.CharField(blank=True, max_length=800, null=True)),
                ('que3', models.CharField(max_length=200)),
                ('option3A', models.CharField(max_length=50)),
                ('option3B', models.CharField(max_length=50)),
                ('option3C', models.CharField(blank=True, max_length=50, null=True)),
                ('option3D', models.CharField(blank=True, max_length=50, null=True)),
                ('image3', models.CharField(blank=True, max_length=800, null=True)),
                ('que4', models.CharField(max_length=200)),
                ('option4A', models.CharField(max_length=50)),
                ('option4B', models.CharField(max_length=50)),
                ('option4C', models.CharField(blank=True, max_length=50, null=True)),
                ('option4D', models.CharField(blank=True, max_length=50, null=True)),
                ('image4', models.CharField(blank=True, max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YouLookLikeRandom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('que', models.CharField(max_length=200)),
                ('optionA', models.CharField(max_length=50)),
                ('optionB', models.CharField(max_length=50)),
                ('optionC', models.CharField(blank=True, max_length=50, null=True)),
                ('optionD', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.CharField(blank=True, max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YouLookLikeScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=4)),
                ('image', models.CharField(max_length=500)),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
