# Generated by Django 3.1.2 on 2021-10-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouLookLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('que', models.CharField(max_length=200)),
                ('optionA', models.CharField(max_length=80)),
                ('optionB', models.CharField(max_length=80)),
                ('optionC', models.CharField(blank=True, max_length=80, null=True)),
                ('optionD', models.CharField(blank=True, max_length=80, null=True)),
                ('image', models.CharField(blank=True, max_length=600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YouLookLikeResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=40)),
                ('image', models.CharField(max_length=600)),
                ('text', models.CharField(max_length=400)),
            ],
        ),
    ]
