# Generated by Django 4.0.6 on 2022-07-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouLookLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('que', models.CharField(max_length=200)),
                ('optionA', models.CharField(max_length=150)),
                ('optionB', models.CharField(max_length=150)),
                ('optionC', models.CharField(blank=True, max_length=150, null=True)),
                ('optionD', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.CharField(blank=True, max_length=600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YouLookLikeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=40)),
                ('image', models.CharField(max_length=600)),
                ('text', models.CharField(max_length=400)),
            ],
        ),
    ]
