# Generated by Django 3.1.2 on 2021-10-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youlooklike', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youlooklikescore',
            name='text',
            field=models.CharField(max_length=400),
        ),
    ]
