# Generated by Django 3.1.2 on 2021-10-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThisOrThat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('optionA', models.CharField(max_length=80)),
                ('optionB', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='WouldYouRather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='all', max_length=30)),
                ('que', models.CharField(max_length=200)),
                ('optionA', models.CharField(max_length=80)),
                ('optionB', models.CharField(max_length=80)),
            ],
        ),
    ]
